# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619d4c9cdbde115f12dbe3ea30e257e52ccdfe46f65a2b198a877534d221a343959d35106f28ca83b080fdf7692d9ede552fcb5825e41a876cec3eaba559564e

test:
  secret_key_base: 66440eb84b89e2c664759720f9e3b9c67956ada5f2064bd1af6838f289ebe6c29da65de54ce179fbbb411d44a275b9615c965f065d7f80490cfcd9cd0506eb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
